name: CI-Rolling

on:
  workflow_dispatch:
  push:
    branches:
      - rolling
  pull_request:
    branches:
      - rolling

env:
  ROS_DISTRO: rolling

jobs:
  industrial_ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    env:
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
